name: Push gem
on:
  push:
    branches: [ main ]
    paths:
      - 'lib/*/version.rb'
jobs:
  publish_gem:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag
    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby
      # Release
      - uses: rubygems/release-gem@v1
      - name: Create GitHub release
        run: |
          tag_name="$(git describe --tags --abbrev=0)"
          release_title="Release version ${tag_name}"
          gh release create "${tag_name}" --verify-tag --generate-notes --title "${release_title}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
