# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.5']
    outputs:
      output1: ${{ steps.pace.outputs.stdout }}
      output2: ${{ steps.timerun.outputs.stdout }}
      output3: ${{ steps.distance.outputs.stdout }} 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rspec
    - id: pace
      run: ruby lib/main.rb p 01:00:00 10
    - id: timerun
      run: ruby lib/main.rb t 00:05:00 12
    - id: distance 
      run: ruby lib/main.rb d 01:30:00 00:05:00
    - name: Check calc results
      run: | 
        echo $output1
        echo $output2
        echo $output3
